#### Python for Data Analysis: Pandas and Numpy
`Coursera course completed 7/20/2022`<br>
`complete listing of the all the code covered in the lectures`<br>
`Task # 1 : Define single and multi-dimensional numpy arrays`

In [59]:
import numpy as np
list_1 = [50, 60, 80, 70, 90]
print(list_1)

[50, 60, 80, 70, 90]


`lets create a numpy array called 'my_array' from 'list_1'`<br>
`my_array = np.array(list_1)`


In [18]:
my_array = np.array(list_1)
my_array

array([50, 60, 80, 70, 90])

`now we find the type of my_numpy_array`

In [19]:
type(my_array)
# should return numpy.ndarray


numpy.ndarray

`now we define a multi dimensional numpy array (matrix`)

In [60]:
my_matrix = np.array([[2,5,8],[7,3,6]])
my_matrix
# should return array([[2,5,8],[7,3,6]])


array([[2, 5, 8],
       [7, 3, 6]])

### Mini challenge
`write code that creates the following 2x4 numpy array :`
`[[3 7 9 3]
 [4 3 2 2]]`

In [21]:
my_matrix = np.array([[3,7, 9, 3],[4,3,2,2]])
my_matrix
# should return 'array([[3,7,9,3],[4,3,2,2]])'

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

#### Task No. 2 numpy methods and functions
`rand normal distribution`

In [22]:
#returns random numbers between 0 and 0 
x = np.random.rand(20)
x


array([0.75207511, 0.26202901, 0.51794188, 0.39648469, 0.38904973,
       0.14640906, 0.7366859 , 0.53955944, 0.09058991, 0.53421939,
       0.81367221, 0.12678019, 0.55920447, 0.98414176, 0.73628544,
       0.59590078, 0.44770271, 0.59796548, 0.11022887, 0.203422  ])

`matrix of random numbers`

In [55]:
#returns a 4 x 4 array of random numbers between 0 and 1
x = np.random.rand(4,4)
x


array([[0.55737756, 0.98550722, 0.5974263 , 0.28527137],
       [0.72279294, 0.54633421, 0.72940148, 0.55943303],
       [0.25225518, 0.00376337, 0.86147619, 0.64053533],
       [0.7990548 , 0.52023678, 0.50605299, 0.08151767]])

`randint is used to generate random integers`
`between upper and lower bounds`

In [56]:
# returs a single random int between 1 and 100
x = np.random.randint(1,100)
x

64

`randint with a certain no of random integers `

In [48]:
# the 1st number in the parens is the lower bound
# the 2nd number is the upper bound
# the 3rd number is the no of random numbers
x = np.random.randint(1,30, 10)
x

array([28,  4, 27,  5, 24, 18, 11, 10, 21, 15])

`arrange creates evenly spaced values within a given interval`

In [26]:
x = np.arange(10,30)
x


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

`create a diagonal of ones and zeros everywhere else`
<br>`use the 'eye' function`

In [27]:
x = np.eye(7)
x


array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

`matrix of ones`

In [28]:
x = np.ones((7,7))
x


array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

`array of zeros`

In [29]:
# an array of 8 zeros
x = np.zeros(8)
x


array([0., 0., 0., 0., 0., 0., 0., 0.])

#### Mini-challenge #2
`code that takes in a pos integer x from the user and` <br> `creates a 1x10 array with random numbers ranging from 0 to x`

In [30]:
y = input('Enter an integer between 2 and 20')
y_int = int(y)
x = np.random.randint(1, y_int, 10)
x

array([15,  5, 10,  5,  8, 18, 13, 16, 18,  3])

#### Task No. 3 Perform math ops in numpy
` np.arange() returns evenly spaced values within an interval`

In [31]:
x = np.arange(3,7)
print('x :', x)
y = np.arange(4,8)
print('y :', y)


x : [3 4 5 6]
y : [4 5 6 7]


`add 2 numpy arrays together`

In [32]:
sum = x + y
sum


array([ 7,  9, 11, 13])

`square an array` <br> `sqrt of an array`

In [33]:
squared = x ** 2
print('squared :', squared)
sqrt = np.sqrt(squared)
print('sqrt of x**2 : ', sqrt)

squared : [ 9 16 25 36]
sqrt of x**2 :  [3. 4. 5. 6.]


`Mini challenge #3`<br>`given x and y values below, obtain the distance between them`
<br>~ x= [5,7,20]
<br>y= [9,15,4] ~

In [34]:
# one way to do it
import numpy as np
x = np.array([5,7,20])
y = np.array([9,15,4])
d = np.sqrt(np.sum(np.square(x-y)))
print('d: ', d)
# the following is correct
a = np.array([5, 7, 20])
b = np.array([9, 15, 4])
e = np.sqrt(x**2 + y**2)
print('e: ', e)

d:  18.33030277982336
e:  [10.29563014 16.55294536 20.39607805]


### Task 4: Perform array slicing and indexing


In [61]:
import numpy as np
my_numpy_array = np.array([3,5,6,2,8,10,20,50])
# access specific index from the numpy array
my_numpy_array[0] # returns the 0 th element of the array


3

`now we will slice out index 0 to 3--(starting with 0 and ending with 2`

In [36]:
my_numpy_array[0:3]


array([3, 5, 6])

`broadcasting and altering several values of a numpy array at once`

In [37]:
my_numpy_array[0:4] = 7
my_numpy_array

array([ 7,  7,  7,  7,  8, 10, 20, 50])

`define a two dim numpy array`

In [38]:
#forms a 4 x 8 array with random numbers between 1 and 100
matrix = np.random.randint(1,100,(4,8))
matrix


array([[ 8, 22, 60, 85, 14, 71, 45, 84],
       [ 6, 22, 28, 67, 13, 21, 90, 55],
       [85, 96, 95, 24,  7, 27, 17, 70],
       [12, 77, 67, 77, 34, 47, 13, 44]])

`get a row from the matrix`

In [39]:
# this code gets the last row in the matrix
matrix[-1]


array([12, 77, 67, 77, 34, 47, 13, 44])

` get one element`

In [40]:
# the two brackets stand for the row and the column
matrix[0][2]


60

#### Mini challenge # 4
` in the following matrix replace the last row with 0`<br>

In [41]:
array1 = np.array([2,30,20,-2,-4])
array2 = np.array([3,4,40,-3,-2])
array3 = np.array([-3,4,-6,90,10])
array4 = np.array([25,45,34,22,12])
array5 = np.array([13,24,22,32,37])

matrix1 = np.array([array1,array2,array3, array4,array5])

matrix1[4]=0
matrix1


array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

#### Task 5 (last numpy task in this notebook) Perform element selection

In [63]:
matrix = np.random.randint(10,20, (5,5))
matrix


array([[19, 10, 13, 10, 15],
       [19, 11, 16, 19, 17],
       [10, 18, 11, 17, 13],
       [11, 19, 13, 10, 13],
       [12, 15, 15, 15, 13]])

`now we will filter on elements that are > 14`

In [66]:
new_matrix = matrix[matrix > 14]
new_matrix


array([19, 15, 19, 16, 19, 17, 18, 17, 19, 15, 15, 15])

`obtain odd elements only`

In [44]:
# if the element of the matrix has a remainder of 1 when it is divided by 2, it is odd
new_matrix_odd = matrix[matrix % 2 == 1 ]
new_matrix_odd


array([13, 11, 15, 13, 19, 19, 17, 19, 17, 11, 19])

### Mini challenge #5
` in the following matrix replace negative elements by 0 and replace odd elements with -2`

In [45]:
matrix[0] = [2,30,20, -2, -4]
matrix[1] = [3, 4, 40, -3, -2]
matrix[2] = [-3, 4, -6, 90, 10]
matrix[3] = [25,45,34,22,12]
matrix[4] = [13, 24, 22, 32, 37]
matrix


array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

`separating out the steps of the challenge -- success!`

In [46]:
matrix[matrix < 0] = 0
matrix[matrix % 2 == 1] = -2
matrix


array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

#### Task 6 Understand Pandas Fundamentals
` pandas are data frames (like spread sheets) built on numpy`

In [2]:

import pandas as pd
fruit =  pd.DataFrame({'Fruit': ['apple', 'peach', 'pear']})
fruit


Fruit
0  apple
1  peach
2   pear

In [49]:
bank_client_df = pd.DataFrame({'Bank Client ID':[111,222,333,444],
            'Bank Client':['Chanel', 'Steve', 'Mitch', 'Ryan'],
            'Net Worth [$]':[3500, 29000, 10000, 2000],
             'Years with bank': [3, 4, 9, 5]})
bank_client_df


Bank Client ID Bank Client  Net Worth [$]  Years with bank
0             111      Chanel           3500                3
1             222       Steve          29000                4
2             333       Mitch          10000                9
3             444        Ryan           2000                5

` two dim data frame `

In [4]:
type(bank_client_df) 

pandas.core.frame.DataFrame

`.head and .tail who the first or last rows of the data frame`

In [54]:
bank_client_df.head(2)
bank_client_df.tail()


Bank Client ID Bank Client  Net Worth [$]  Years with bank
0             111      Chanel           3500                3
1             222       Steve          29000                4
2             333       Mitch          10000                9
3             444        Ryan           2000                5

#### Mini challenge 6
`define a dataframe 'portfolio_df' that contains 3 stock ticker symbols, number of shares` <br>`and price per share. Calculate total value of the portfolio including all stocks`

In [53]:
portfolio_df = pd.DataFrame({'Stock Ticker':['TSLA', 'BRK.B', 'AMZN'], 
        "Today's Price": [80, 150, 100], 
        'No of shares': [736.59, 283.55, 118.21]})
portfolio_df.columns


Index(['Stock Ticker', 'Today's Price', 'No of shares'], dtype='object')

`stocks_dollar_value = portfolio_df["Today's Price"] * portfolio_df['No of shares']`

In [52]:
stocks_dollar_value = portfolio_df["Today's Price"] * portfolio_df['No of shares']
print('Stocks dollar value',stocks_dollar_value)
stocks_dollar_value.sum()


Stocks dollar value 0    58927.2
1    42532.5
2    11821.0
dtype: float64


113280.70000000001

#### Task #7: `Pandas with CSV and HTML data`<br>`use pd.read_html('')`<br>`https://www.ssa.gov/oact/progdata/nra.html`

In [ ]:
house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
house_price_df[0]

#retirement_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
#retirement_df


# lxml needed to read .xml %pip used to install into jupythe notebook. !pip to install into python
installing pip   %pip install lxml
                    !python -m pip install --upgrade pip


In [64]:
%pip install lxml



Note: you may need to restart the kernel to use updated packages.


#### Mini Challenge # 7
`read tabular US retirement data`<br>`use data from https://www.ssa.gov/oact/progdata/nra.html`


In [ ]:
# can't get this code to run--error message pandas has not attribute read_html
retirement_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_df


#### Task #8 pandas operations
`use bank_client_df to only select high net worth individual with min $5000+ net worth.` 

In [73]:
bank_client_df = pd.DataFrame({'Bank Client ID':[111,222,333,444],
            'Bank Client':['Chanel', 'Steve', 'Mitch', 'Ryan'],
            'Net Worth [$]':[3500, 29000, 10000, 2000],
             'Years with bank': [3, 4, 9, 5]})
bank_client_df


Bank Client ID Bank Client  Net Worth [$]  Years with bank
0             111      Chanel           3500                3
1             222       Steve          29000                4
2             333       Mitch          10000                9
3             444        Ryan           2000                5

In [76]:
df_loyal = bank_client_df[bank_client_df['Years with bank'] >= 5 ]
df_loyal


Bank Client ID Bank Client  Net Worth [$]  Years with bank
2             333       Mitch          10000                9
3             444        Ryan           2000                5

`delete a column from a DataFrame`

In [77]:
del bank_client_df['Bank Client ID']
bank_client_df


Bank Client  Net Worth [$]  Years with bank
0      Chanel           3500                3
1       Steve          29000                4
2       Mitch          10000                9
3        Ryan           2000                5

`select only high networth individuals with min $5000`<br>
`combined networth for all customers over $5000.`

In [79]:
high_networth_df = bank_client_df[bank_client_df['Net Worth [$]'] > 5000]
high_networth_df

<bound method NDFrame._add_numeric_operations.<locals>.sum of   Bank Client  Net Worth [$]  Years with bank
1       Steve          29000                4
2       Mitch          10000                9>

`now try to get just the Net Worth column by itself to do a .sum()`<br>
`following the word sum must be a () to have the sum print`

In [91]:
high_networth = high_networth_df['Net Worth [$]'].sum()
high_networth


39000

#### Task #9 Pandas with Functions


In [92]:
bank_client_df


Bank Client  Net Worth [$]  Years with bank
0      Chanel           3500                3
1       Steve          29000                4
2       Mitch          10000                9
3        Ryan           2000                5

`define a function that increases Net worth [$] by 20%

In [100]:
def networth_update(balance) :
    return balance * 1.2
    

In [101]:
# apply a function to the dataFrame
print(bank_client_df['Net Worth [$]'].apply(networth_update))
#bank_client_df['Bank Client'].apply(len) #use apply to find the len of name


0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net Worth [$], dtype: float64


#### Mini challenge #9
`1. def a function that triples the net worth [$] and adds $200`<br>
`2. apply the function to the DataFrame`<br>
`3. Calc updated net worth of all clients combined`

In [102]:
def networth_update(balance) :
    return balance * 3 + 200
#bank_client_df['Net worth [$]'].apply(networth_update)

    

In [105]:
results = bank_client_df['Net Worth [$]'].apply(networth_update)
results.sum()


134300

In [106]:
results.sum()


134300

#### Task # 10 perform sorting and ordering in pandas

In [7]:
bank_client_df = pd.DataFrame({'Bank client ID': [111,222,333,444],
                                'Bank Client Name':['Channel', 'Steve', 'Mitch', 'Ryan'],
                                'Net worth [$]':[3500, 29000, 10000, 2000],
                                'Years with bank':[3,4,9,5]})
bank_client_df


Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111          Channel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [110]:
# sort the values in the df according to no of years with bank
bank_client_df.sort_values(by = 'Years with bank')


Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111          Channel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [112]:
# set inplace = True to ensure that change has taken place in memory
bank_client_df.sort_values(by = 'Years with bank', inplace = True)


### Task # 11 Concatenating and Merging

In [22]:
# https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html
df1 = pd.DataFrame({'A':['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3'],
    'C': ['C0', 'C1', 'C2', 'C3'],
    'D': ['D0', 'D1', 'D2', 'D3']},
    index = [0, 1, 2, 3])


In [23]:
df1


A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [24]:
# https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html
df2 = pd.DataFrame({'A':['A4', 'A5', 'A6', 'A7'],
    'B': ['B4', 'B5', 'B6', 'B7'],
    'C': ['C4', 'C5', 'C6', 'C7'],
    'D': ['D4', 'D5', 'D6', 'D7']},
    index = [4, 5, 6, 7])


In [25]:
df2


A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [26]:
df3 = pd.DataFrame({'A':['A8', 'A9', 'A10', 'A11'],
    'B': ['B8', 'B9', 'B10', 'B11'],
    'C': ['C8', 'C9', 'C10', 'C11'],
    'D': ['D8', 'D9', 'D10', 'D11']},
    index = [8, 9, 10, 11])

In [27]:
df3


A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [28]:
pd.concat([df1, df2, df3])


A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

#### Task # 12 Project and concluding remarks
`1. define dataframe named Bank_df_1 that contains first and last names for bank clients with IDs 1,2,3,4,and 5`<br>`2. Assume that the bank got 5 new clients, define another dataframe named Bank_df_2 with clients 6,7,8,9,10`<br>`3. we obtain additional info (Annual Salary) about all our bank customers 10 customers`<br>`4. concatenate both 'Bank_df_1' and 2`<br>`5. merge client names and their newly added salary information using the 'Bank Client ID`<br>`6. assume you became a new client to the bank`<br>`7. define new dataframe that contains your info such as client ID -- choose 11, first name last name and annual salary`<br>`8. add to the original dataframe 'bank_df_all'`


In [29]:
bank_df_1 = pd.DataFrame({'ID':[1,2,3,4,5],
                        'Client First Name': ['Never', 'Forget', 'Rule', '# 1', 'Warren'],
                        'Client Last Name': ['Python', 'in a Nutshell', 'Quick', 'Reference', 'Buffett']})
bank_df_1



ID Client First Name Client Last Name
0   1             Never           Python
1   2            Forget    in a Nutshell
2   3              Rule            Quick
3   4               # 1        Reference
4   5            Warren          Buffett

In [30]:
bank_df_2 = pd.DataFrame({'ID': [6,7,8,9,10],
                        'Client First Name': ['Bioinformatics', 'Data', 'Skills', 'Reproducible', 'Vince'],
                        'Client Last Name': ['Python', 'All-in-One', 'for Dummies', '7 Books in One', 'Buffalo']})
bank_df_2


ID Client First Name Client Last Name
0   6    Bioinformatics           Python
1   7              Data       All-in-One
2   8            Skills      for Dummies
3   9      Reproducible   7 Books in One
4  10             Vince          Buffalo

In [33]:
# concatenate bank_df_1 and 2
bank_df_all = pd.concat([bank_df_1, bank_df_2])
bank_df_all
           

ID Client First Name Client Last Name
0   1             Never           Python
1   2            Forget    in a Nutshell
2   3              Rule            Quick
3   4               # 1        Reference
4   5            Warren          Buffett
0   6    Bioinformatics           Python
1   7              Data       All-in-One
2   8            Skills      for Dummies
3   9      Reproducible   7 Books in One
4  10             Vince          Buffalo

In [35]:
# add annual salary for all bank customers
# in bank_df_all
bank_all_salaries = pd.DataFrame({'ID': [1,2,3,4,5,6,7,8,9,10],
                'Annual Salary': [55000, 65000, 70000, 72000, 74000, 86000, 89000, 89500, 71000, 65002]})
bank_all_salaries


ID  Annual Salary
0   1          55000
1   2          65000
2   3          70000
3   4          72000
4   5          74000
5   6          86000
6   7          89000
7   8          89500
8   9          71000
9  10          65002

In [38]:
# merging bank_all_salaries with bank_df_all
bank_df_all = pd.merge(bank_df_all, bank_all_salaries)
bank_df_all



ID Client First Name Client Last Name  Annual Salary
0   1             Never           Python          55000
1   2            Forget    in a Nutshell          65000
2   3              Rule            Quick          70000
3   4               # 1        Reference          72000
4   5            Warren          Buffett          74000
5   6    Bioinformatics           Python          86000
6   7              Data       All-in-One          89000
7   8            Skills      for Dummies          89500
8   9      Reproducible   7 Books in One          71000
9  10             Vince          Buffalo          65002

In [40]:
bank_df_me = pd.DataFrame({'ID': [11],
                'Client First Name': ['Rich'],
                'Client Last Name': ['Potter'],
                'Annual Salary': [110555]})
bank_df_me


ID Client First Name Client Last Name  Annual Salary
0  11              Rich           Potter         110555

`now we are ready to add the row with Rich Potter to the bank_df as the last row.`
`this involves a concat of bank_df_all with bank_df_me`

In [44]:
bank_df_total = pd.concat([bank_df_all, bank_df_me])
bank_df_total


ID Client First Name Client Last Name  Annual Salary
0   1             Never           Python          55000
1   2            Forget    in a Nutshell          65000
2   3              Rule            Quick          70000
3   4               # 1        Reference          72000
4   5            Warren          Buffett          74000
5   6    Bioinformatics           Python          86000
6   7              Data       All-in-One          89000
7   8            Skills      for Dummies          89500
8   9      Reproducible   7 Books in One          71000
9  10             Vince          Buffalo          65002
0  11              Rich           Potter         110555